apiVersion: apps/v1
kind: Deployment
metadata:
  name: lightweather
  namespace: gohome
  labels:
    app: lightweather
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lightweather
  template:
    metadata:
      labels:
        app: lightweather
    spec:
      containers:
        - name: lightweather
          image: registry.home-k3s.lab/gohome/lightweather:v6
          ports:
            - containerPort: 3040
              name: http
          env:
            - name: OWM_API_KEY
              valueFrom:
                secretKeyRef:
                  name: owm-api-key-secret
                  key: OWM_API_KEY
            - name: HUE_ID
              valueFrom:
                secretKeyRef:
                  name: hue-id-secret
                  key: HUE_ID
          volumeMounts:
            - name: config-volume
              mountPath: /etc/config.yml
              subPath: config.yml
          command: ["/app/lightweather"]
          args: ["-c", "/etc/config.yml"]
      imagePullSecrets:
      - name: home-k3s-registry
      volumes:
        - name: config-volume
          configMap:
            name: lightweather-config
