apiVersion: v1
kind: Secret
metadata:
  name: owm-api-key-secret
type: Opaque
data:
  OWM_API_KEY: ${OWM_API_KEY_BASE64}

---
apiVersion: v1
kind: Secret
metadata:
  name: hue-id-secret
type: Opaque
data:
  HUE_ID: ${HUE_ID_BASE64}
