apiVersion: v1
kind: Service
metadata:
  name: lightweather-service
  namespace: gohome
spec:
  selector:
    app: lightweather
  ports:
    - protocol: TCP
      port: 3040
      targetPort: 3040
  type: LoadBalancer
