---
unit: "C"
lang: "EN"
location: "Calgary, CA"
hue_id: ""
hue_ip_address: "192.168.57.231"
owm_api_key: ""
light_name: "Office side light"

max_color: red

colors:
  - color: orange
    threshold: 25
  - color: green
    threshold: 15
  - color: yellow
    threshold: 0
  - color: blue
    threshold: -20
  - color: purple
    threshold: -10
  - color: red
    threshold: 30