apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: gohome

configMapGenerator:
    - name: lightscheduler-config
      files:
          - base/config.yml

resources:
    - deployment.yaml
    - service.yaml
    - ingress.yaml
    - secrets.yaml
