---
global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s
alerting:
  alertmanagers:
    - timeout: 10s
      api_version: v2
      path_prefix: /
      scheme: http
      follow_redirects: true
      enable_http2: true
      static_configs:
        - targets: []
scrape_configs:
  - job_name: prometheus
    honor_timestamps: true
    scrape_interval: 15s
    scrape_timeout: 10s
    metrics_path: /metrics
    scheme: http
    follow_redirects: true
    enable_http2: true
    static_configs:
      - targets:
          - localhost:9090
  - job_name: svc_discovery
    file_sd_configs:
    - files:
      - '/prometheus/sd_*.json'
      - '/prometheus/sd_*.yml'
      - '/prometheus/sd_*.yaml'
      refresh_interval: "30s"
  - job_name: pve_exporter
    static_configs:
      - targets:
          - 192.168.227.2 # Proxmox VE node.
          - 192.168.227.3
          - 192.168.227.250
    metrics_path: /pve
    params:
      module: [default]
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 192.168.57.71:9221 # PVE exporter.
